// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorPageWatches.Data;

#nullable disable

namespace RazorPageWatches.Migrations
{
    [DbContext(typeof(RazorPageWatchesContext))]
    [Migration("20260121045324_SeedingData")]
    partial class SeedingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RazorPageWatches.Models.Watch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Watch");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Rolex",
                            Model = "Watchless",
                            Price = 4223m,
                            ReleaseDate = new DateTime(2026, 1, 21, 12, 53, 23, 716, DateTimeKind.Local).AddTicks(4527)
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Omega",
                            Model = "Timekeeper",
                            Price = 5599m,
                            ReleaseDate = new DateTime(2026, 1, 21, 12, 53, 23, 716, DateTimeKind.Local).AddTicks(4537)
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Tag Heuer",
                            Model = "ChronoMaster",
                            Price = 3150m,
                            ReleaseDate = new DateTime(2026, 1, 21, 12, 53, 23, 716, DateTimeKind.Local).AddTicks(4538)
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Omega",
                            Model = "Aqua Terra",
                            Price = 4975m,
                            ReleaseDate = new DateTime(2026, 1, 21, 12, 53, 23, 716, DateTimeKind.Local).AddTicks(4539)
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Rolex",
                            Model = "Explorer",
                            Price = 7800m,
                            ReleaseDate = new DateTime(2026, 1, 21, 12, 53, 23, 716, DateTimeKind.Local).AddTicks(4540)
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Omega",
                            Model = "Speedmaster",
                            Price = 5500m,
                            ReleaseDate = new DateTime(2026, 1, 21, 12, 53, 23, 716, DateTimeKind.Local).AddTicks(4542)
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Rolex",
                            Model = "Submariner",
                            Price = 9400m,
                            ReleaseDate = new DateTime(2026, 1, 21, 12, 53, 23, 716, DateTimeKind.Local).AddTicks(4543)
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Tag Heuer",
                            Model = "Carrera",
                            Price = 4200m,
                            ReleaseDate = new DateTime(2026, 1, 21, 12, 53, 23, 716, DateTimeKind.Local).AddTicks(4544)
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Omega",
                            Model = "Seamaster",
                            Price = 3800m,
                            ReleaseDate = new DateTime(2026, 1, 21, 12, 53, 23, 716, DateTimeKind.Local).AddTicks(4545)
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Rolex",
                            Model = "Daytona",
                            Price = 13500m,
                            ReleaseDate = new DateTime(2026, 1, 21, 12, 53, 23, 716, DateTimeKind.Local).AddTicks(4545)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
