// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorPageWatches.Data;

#nullable disable

namespace RazorPageWatches.Migrations
{
    [DbContext(typeof(RazorPageWatchesContext))]
    [Migration("20260130050421_AddRatingToWatch")]
    partial class AddRatingToWatch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RazorPageWatches.Models.Watch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Watch");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Rolex",
                            Model = "Watchless",
                            Price = 4223m,
                            Rating = 0m,
                            ReleaseDate = new DateTime(2026, 1, 30, 13, 4, 20, 401, DateTimeKind.Local).AddTicks(8256)
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Omega",
                            Model = "Timekeeper",
                            Price = 5599m,
                            Rating = 0m,
                            ReleaseDate = new DateTime(2026, 1, 30, 13, 4, 20, 401, DateTimeKind.Local).AddTicks(8267)
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Tag Heuer",
                            Model = "ChronoMaster",
                            Price = 3150m,
                            Rating = 0m,
                            ReleaseDate = new DateTime(2026, 1, 30, 13, 4, 20, 401, DateTimeKind.Local).AddTicks(8269)
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Omega",
                            Model = "Aqua Terra",
                            Price = 4975m,
                            Rating = 0m,
                            ReleaseDate = new DateTime(2026, 1, 30, 13, 4, 20, 401, DateTimeKind.Local).AddTicks(8270)
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Rolex",
                            Model = "Explorer",
                            Price = 7800m,
                            Rating = 0m,
                            ReleaseDate = new DateTime(2026, 1, 30, 13, 4, 20, 401, DateTimeKind.Local).AddTicks(8271)
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Omega",
                            Model = "Speedmaster",
                            Price = 5500m,
                            Rating = 0m,
                            ReleaseDate = new DateTime(2026, 1, 30, 13, 4, 20, 401, DateTimeKind.Local).AddTicks(8272)
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Rolex",
                            Model = "Submariner",
                            Price = 9400m,
                            Rating = 0m,
                            ReleaseDate = new DateTime(2026, 1, 30, 13, 4, 20, 401, DateTimeKind.Local).AddTicks(8274)
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Tag Heuer",
                            Model = "Carrera",
                            Price = 4200m,
                            Rating = 0m,
                            ReleaseDate = new DateTime(2026, 1, 30, 13, 4, 20, 401, DateTimeKind.Local).AddTicks(8275)
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Omega",
                            Model = "Seamaster",
                            Price = 3800m,
                            Rating = 0m,
                            ReleaseDate = new DateTime(2026, 1, 30, 13, 4, 20, 401, DateTimeKind.Local).AddTicks(8276)
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Rolex",
                            Model = "Daytona",
                            Price = 13500m,
                            Rating = 0m,
                            ReleaseDate = new DateTime(2026, 1, 30, 13, 4, 20, 401, DateTimeKind.Local).AddTicks(8277)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
